"""removed unique on num chapters

Revision ID: ab4c9f83789f
Revises: 3f5a17e7f212
Create Date: 2019-07-24 20:04:42.702803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab4c9f83789f'
down_revision = '3f5a17e7f212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('num_chapters', table_name='book_ref')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('num_chapters', 'book_ref', ['num_chapters'], unique=True)
    # ### end Alembic commands ###
