"""empty message

Revision ID: f2fa0cdec157
Revises: de30f32b067c
Create Date: 2020-01-21 22:07:35.017448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fa0cdec157'
down_revision = 'de30f32b067c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('highlight_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'highlight_color')
    # ### end Alembic commands ###
